### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by vincent-olivert-riera**

### CODE REVIEW

**Comment by vincent-olivert-riera** [comment]
@barnumbirr , sorry about the push force I did after creating the PR. I had to fix some typos in a commit message.

The PR is now ready for review. Thanks.

**Comment by vincent-olivert-riera** [comment]
@barnumbirr , hello?

**Comment by barnumbirr** [comment]
@vincent-olivert-riera my bad, I completely forgot about this. Thank you for proposing your changes however I'm not sure I want to merge them:
The proposed changes don't improve how the packages are built from a `Github Actions` point of view.

There's also an ongoing effort to create an actual Action for building Debian packages making all the shell scripts in this repository obsolete.

**Comment by vincent-olivert-riera** [comment]
No problem at all. Thanks for answering.

**Pull request closed without merging**
